name: aarch64-test

on:
  workflow_dispatch:

jobs:
  linux-aarch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python-version }}'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          target: aarch64-unknown-linux-gnu
          default: true
          
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
  
      - uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: Gr1N/setup-poetry@v9

      - name: Setup project
        run: |
          just bootstrap-python

      - uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: stable
          container: ghcr.io/rust-cross/manylinux_2_28-cross:aarch64	
          command: build
          args: -m connectorx-python/Cargo.toml -i python${{ matrix.python-version }} --release --target aarch64-unknown-linux-gnu --manylinux 2_28 --features integrated-auth-gssapi
          before-script-linux: |
              # If we're running on debian-based system.
              apt-get update -y
              apt-get install -y libssl-dev openssl pkg-config libkrb5-dev clang
        env:
          SQLITE3_STATIC: 1

      - name: Copy j4rs dependencies into dist
        run: |
          cp -rf connectorx-python/target/release/jassets connectorx-python/connectorx/dependencies

      # rebuild the wheel to incorporate j4rs dependencies
      - uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: stable
          container: ghcr.io/rust-cross/manylinux_2_28-cross:aarch64	
          command: build
          args: -m connectorx-python/Cargo.toml -i python${{ matrix.python-version }} --release --target aarch64-unknown-linux-gnu --manylinux 2_28 --features integrated-auth-gssapi
          before-script-linux: |
              # If we're running on debian-based system.
              apt-get update -y
              apt-get install -y libssl-dev openssl pkg-config libkrb5-dev clang
        env:
          SQLITE3_STATIC: 1

      - uses: actions/upload-artifact@v4
        with:
          name: "ubuntu-latest-${{ matrix.python-version }}"
          path: connectorx-python/target/wheels/*.whl
